<?php

namespace Sch\WlBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CircleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CircleRepository extends EntityRepository
{
}
