<?php

namespace Sch\WlBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * WishRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WishRepository extends EntityRepository
{
    public function findAllForUser($user, $limit = 50)
    {
        $query = $this->createQueryBuilder('d')
        ->where('d.user = :user')
        ->setParameter('user', $user)
        ->setMaxResults($limit)
        ->getQuery();

        return $query->getResult();
    }
}
